// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqj4UO2c2SdHQZJAvYEJhR0y186ELq9Yk',
    appId: '1:268226737835:web:6a1c8163e4ade1f95ba9ee',
    messagingSenderId: '268226737835',
    projectId: 'socialapp-98f4b',
    authDomain: 'socialapp-98f4b.firebaseapp.com',
    storageBucket: 'socialapp-98f4b.appspot.com',
    measurementId: 'G-HSECH9LZZ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXUvgxt2K-FGKlfJrnrvN2E9vh0YP-jaI',
    appId: '1:268226737835:android:664cfa3a977b19155ba9ee',
    messagingSenderId: '268226737835',
    projectId: 'socialapp-98f4b',
    storageBucket: 'socialapp-98f4b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz2qzOFlzso2-gp2Z-pjh2aN6fLgtmWsg',
    appId: '1:268226737835:ios:8a4779c02cdeafb15ba9ee',
    messagingSenderId: '268226737835',
    projectId: 'socialapp-98f4b',
    storageBucket: 'socialapp-98f4b.appspot.com',
    iosBundleId: 'com.example.profilepage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz2qzOFlzso2-gp2Z-pjh2aN6fLgtmWsg',
    appId: '1:268226737835:ios:8a4779c02cdeafb15ba9ee',
    messagingSenderId: '268226737835',
    projectId: 'socialapp-98f4b',
    storageBucket: 'socialapp-98f4b.appspot.com',
    iosBundleId: 'com.example.profilepage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqj4UO2c2SdHQZJAvYEJhR0y186ELq9Yk',
    appId: '1:268226737835:web:2089ed437e4c12115ba9ee',
    messagingSenderId: '268226737835',
    projectId: 'socialapp-98f4b',
    authDomain: 'socialapp-98f4b.firebaseapp.com',
    storageBucket: 'socialapp-98f4b.appspot.com',
    measurementId: 'G-GVTB2S1RQK',
  );
}
